package com.example.app_dich_quet_van_ban.presentation.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.app_dich_quet_van_ban.presentation.theme.AppDichQuetVanBanTheme
import com.example.app_dich_quet_van_ban.presentation.viewmodel.ScanResultViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable

fun ScanResultScreen(
    scannedText: String,
    onNavigateBack: () -> Unit,
    onSaveComplete: (fileName: String, content: String, type: String) -> Unit,
    viewModel: ScanResultViewModel = viewModel()
) {
    // 1. Tự động tạo tên mặc định từ văn bản quét
    val autoGeneratedName = remember(scannedText) {
        scannedText.trim().split("\\s+".toRegex())
            .take(5).joinToString("_")
            .filter { it.isLetterOrDigit() || it == '_' }
            .ifEmpty { "Tai_lieu_${System.currentTimeMillis()/1000}" }
    }

    // 2. State lưu tên file - ban đầu lấy tên tự động
    var fileName by remember { mutableStateOf(autoGeneratedName) }
    var textState by remember { mutableStateOf(scannedText) }

// Gán tên mặc định này vào state để người dùng có thể sửa lại nếu muốn

    // --- LOGIC CHUYỂN ĐỔI TAB ---
    // 0: Nguyên bản, 1: Tóm tắt
    var selectedTab by remember { mutableIntStateOf(0) }
    var summaryText by remember { mutableStateOf("") }
    var isLoading by remember { mutableStateOf(false) }

    val scrollState = rememberScrollState()

    Scaffold(
        topBar = {
            CenterAlignedTopAppBar(
                title = { Text("Chi tiết văn bản", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onNavigateBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .padding(16.dp)
        ) {
            // 1. Nhập tên file
            OutlinedTextField(
                value = fileName,
                onValueChange = { fileName = it },
                label = { Text("Tên tệp lưu trữ") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                shape = RoundedCornerShape(12.dp)
            )

            Spacer(modifier = Modifier.height(16.dp))

            // 2. THANH CHỌN TAB (Nút bấm chuyển đổi)
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(
                        MaterialTheme.colorScheme.primary.copy(alpha = 0.05f),
                        RoundedCornerShape(12.dp)
                    )
                    .padding(4.dp)
            ) {
                // Nút Nguyên bản
                TabButton(
                    text = "Nguyên bản",
                    isSelected = selectedTab == 0,
                    modifier = Modifier.weight(1f),
                    onClick = { selectedTab = 0 }
                )

                // Nút Tóm tắt
                TabButton(
                    text = "Tóm tắt AI",
                    isSelected = selectedTab == 1,
                    modifier = Modifier.weight(1f),
                    onClick = {
                        selectedTab = 1
                        // CHỈ GỌI AI NẾU CHƯA CÓ TÓM TẮT
                        if (summaryText.isEmpty() && !isLoading) {
                            isLoading = true
                            viewModel.summarizeText(textState) { result ->
                                summaryText = result
                                isLoading = false
                            }
                        }
                    }
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            // 3. KHUNG HIỂN THỊ NỘI DUNG DUY NHẤT
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surface
                ),
                border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant)
            ) {
                Box(modifier = Modifier.fillMaxSize().padding(16.dp)) {
                    if (isLoading) {
                        // Hiển thị khi đang chờ AI phản hồi
                        Column(
                            modifier = Modifier.align(Alignment.Center),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            CircularProgressIndicator(color = MaterialTheme.colorScheme.primary)
                            Spacer(modifier = Modifier.height(8.dp))
                            Text("AI đang suy nghĩ...", style = MaterialTheme.typography.bodyMedium)
                        }
                    } else {
                        // Hiển thị nội dung dựa trên Tab đang chọn
                        Column(modifier = Modifier.verticalScroll(scrollState)) {
                            Text(
                                text = if (selectedTab == 0) textState else summaryText.ifEmpty { "Nhấn tab Tóm tắt để AI phân tích..." },
                                style = MaterialTheme.typography.bodyLarge,
                                color = MaterialTheme.colorScheme.onSurface,
                                lineHeight = 24.sp
                            )
                        }

                        // Nút Copy nhanh
                        IconButton(
                            onClick = { /* Logic Copy */ },
                            modifier = Modifier.align(Alignment.BottomEnd)
                        ) {
                            Icon(Icons.Default.ContentCopy, null, tint = MaterialTheme.colorScheme.primary)
                        }
                    }
                }
            }

            // 4. Thanh điều hướng dưới cùng
            Row(
                modifier = Modifier.padding(top = 16.dp),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = onNavigateBack,
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Text("Thoát")
                }

                Button(
                    onClick = { viewModel.saveOrUpdateDocument(
                        fileName,
                        textState,
                        "Word") },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.primary
                    )
                ) {
                    Text("Lưu file Word")
                }
            }
        }
    }
}

// Composable phụ cho nút Tab
@Composable
fun TabButton(
    text: String,
    isSelected: Boolean,
    modifier: Modifier = Modifier,
    onClick: () -> Unit
) {
    Button(
        onClick = onClick,
        modifier = modifier,
        shape = RoundedCornerShape(10.dp),
        colors = ButtonDefaults.buttonColors(
            containerColor = if (isSelected) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceVariant,
            contentColor = if (isSelected) MaterialTheme.colorScheme.onPrimary else MaterialTheme.colorScheme.onSurfaceVariant
        ),
        elevation = null
    ) {
        Text(text, fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal)
    }
}
@Preview(showBackground = true, showSystemUi = true)
@Composable
fun ScanResultScreenPreview() {
    AppDichQuetVanBanTheme {
        // Tạo một nội dung mẫu dài để test tính năng cuộn
        val sampleText = """
            Quy tắc đạo đức trong công ty công nghệ bao gồm các quy tắc quan trọng. 
            Đầu tiên là tính minh bạch trong thuật toán. Thứ hai là bảo mật dữ liệu người dùng. 
            Thứ ba là trách nhiệm xã hội của các kỹ sư phần mềm. 
            Việc tuân thủ các quy tắc này giúp xây dựng niềm tin với khách hàng.
        """.trimIndent()

        Surface(
            modifier = Modifier.fillMaxSize(),
            color = MaterialTheme.colorScheme.background
        ) {
            ScanResultScreen(
                scannedText = sampleText,
                onNavigateBack = { /* Không làm gì trong Preview */ },
                onSaveComplete = { fileName, content, type ->
                    println("Đã lưu $fileName dạng $type")
                }
                // Lưu ý: Trong thực tế, bạn nên dùng MockViewModel nếu app phức tạp,
                // nhưng với bài tập này, truyền tham số như trên là đủ để hiện giao diện.
            )
        }
    }
}